# Generated by Django 5.0.6 on 2025-05-30 09:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company going public', max_length=200)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/')),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='Total issue size in crores', max_digits=12)),
                ('price_band_min', models.DecimalField(decimal_places=2, help_text='Minimum price per share', max_digits=10)),
                ('price_band_max', models.DecimalField(decimal_places=2, help_text='Maximum price per share', max_digits=10)),
                ('lot_size', models.PositiveIntegerField(help_text='Minimum number of shares per application')),
                ('issue_open_date', models.DateField(help_text='Date when IPO opens for subscription')),
                ('issue_close_date', models.DateField(help_text='Date when IPO closes for subscription')),
                ('listing_date', models.DateField(blank=True, help_text='Expected listing date on stock exchange', null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open for Subscription'), ('CLOSED', 'Closed'), ('ALLOTMENT', 'Allotment Process'), ('LISTED', 'Listed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', help_text='Current status of the IPO', max_length=15)),
                ('retail_allocation', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Percentage allocated for retail investors', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hni_allocation', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Percentage allocated for HNI investors', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qib_allocation', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percentage allocated for QIB investors', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('face_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Face value per share', max_digits=8)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Expected market capitalization in crores', max_digits=15, null=True)),
                ('listing_exchange', models.CharField(choices=[('BSE', 'Bombay Stock Exchange'), ('NSE', 'National Stock Exchange'), ('BOTH', 'Both BSE and NSE')], default='BOTH', help_text='Stock exchange for listing', max_length=10)),
                ('prospectus_url', models.URLField(blank=True, help_text='URL to IPO prospectus document', null=True)),
                ('drhp_url', models.URLField(blank=True, help_text='URL to Draft Red Herring Prospectus', null=True)),
                ('description', models.TextField(help_text='Brief description about the company and IPO')),
                ('objectives', models.TextField(blank=True, help_text='Objects of the issue', null=True)),
                ('total_subscription', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total subscription times (e.g., 2.5x)', max_digits=8)),
                ('retail_subscription', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retail category subscription times', max_digits=8)),
                ('hni_subscription', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='HNI category subscription times', max_digits=8)),
                ('qib_subscription', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='QIB category subscription times', max_digits=8)),
                ('registrar_name', models.CharField(blank=True, help_text='Name of the registrar', max_length=200, null=True)),
                ('lead_managers', models.TextField(blank=True, help_text='Lead managers for the IPO (comma separated)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'db_table': 'ipos',
                'ordering': ['-issue_open_date'],
            },
        ),
    ]
