# Generated by Django 5.0.6 on 2025-05-30 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique application ID', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Number of shares applied for', validators=[django.core.validators.MinValueValidator(1)])),
                ('bid_price', models.DecimalField(decimal_places=2, help_text='Price per share bid by the applicant', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total application amount', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('ALLOTTED', 'Allotted'), ('NOT_ALLOTTED', 'Not Allotted'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the application', max_length=15)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('BLOCKED', 'Amount Blocked'), ('CONFIRMED', 'Payment Confirmed'), ('REFUNDED', 'Amount Refunded'), ('FAILED', 'Payment Failed')], default='PENDING', help_text='Payment status', max_length=15)),
                ('bank_name', models.CharField(help_text='Bank for ASBA mandate', max_length=100)),
                ('bank_account_number', models.CharField(help_text='Bank account number for ASBA', max_length=20)),
                ('allotted_quantity', models.PositiveIntegerField(default=0, help_text='Number of shares allotted')),
                ('allotment_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final allotment price per share', max_digits=10, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be refunded', max_digits=15)),
                ('application_number', models.CharField(blank=True, help_text='Application number from registrar', max_length=20, null=True, unique=True)),
                ('pan_number', models.CharField(help_text='PAN number used for application', max_length=10)),
                ('demat_account', models.CharField(help_text='Demat account for share credit', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('allotment_date', models.DateTimeField(blank=True, null=True)),
                ('ipo', models.ForeignKey(help_text='IPO for which application is made', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ipos.ipo')),
                ('user', models.ForeignKey(help_text='User who applied for the IPO', on_delete=django.db.models.deletion.CASCADE, related_name='ipo_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPO Application',
                'verbose_name_plural': 'IPO Applications',
                'db_table': 'ipo_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'ipo')},
            },
        ),
        migrations.CreateModel(
            name='BidDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, help_text='Bid price for this lot', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Number of shares for this bid price', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='Related IPO application', on_delete=django.db.models.deletion.CASCADE, related_name='bid_details', to='applications.ipoapplication')),
            ],
            options={
                'verbose_name': 'Bid Detail',
                'verbose_name_plural': 'Bid Details',
                'db_table': 'bid_details',
                'ordering': ['-bid_price'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('APPLICATION_FORM', 'Application Form'), ('ASBA_FORM', 'ASBA Form'), ('PAN_CARD', 'PAN Card'), ('BANK_STATEMENT', 'Bank Statement'), ('DEMAT_STATEMENT', 'Demat Statement'), ('OTHER', 'Other')], help_text='Type of document', max_length=20)),
                ('document_file', models.FileField(help_text='Uploaded document file', upload_to='application_documents/')),
                ('description', models.CharField(blank=True, help_text='Document description', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='Related IPO application', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.ipoapplication')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'db_table': 'application_documents',
            },
        ),
    ]
